name: Auto Create Pull Request and Merge
on:
  push:
    branches-ignore:
      - main  # ทำงานทุกกิ่ง ยกเว้น main
  
jobs:
  create-and-merge:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ขั้นตอนที่ 1: สร้าง PR
      - name: Create Pull Request
        id: cpr_step
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: "main"
          pr_title: "Auto-Merge: งานจากกิ่ง ${{ github.ref_name }}"
          pr_body: "ระบบอัตโนมัติ: สร้าง PR, Merge และจะลบกิ่งทิ้งทันที"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_allow_empty: false 

      # ขั้นตอนตรวจสอบ: ถ้าไม่มีเลข PR (คือไฟล์ซ้ำกันเป๊ะ) ให้ข้าม
      - name: Check output
        run: |
          if [ -z "${{ steps.cpr_step.outputs.pr_number }}" ]; then
            echo "⚠️ ไม่พบความเปลี่ยนแปลง หรือ PR ถูกสร้างไปแล้ว"
          else
            echo "✅ สร้าง PR หมายเลข ${{ steps.cpr_step.outputs.pr_number }} สำเร็จ"
          fi

      # ขั้นตอนที่ 2: สั่ง Merge และลบกิ่งทันที
      - name: Merge and Delete Branch
        # ทำเฉพาะถ้ามีเลข PR ส่งมา
        if: ${{ steps.cpr_step.outputs.pr_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🚀 กำลัง Merge PR หมายเลข ${{ steps.cpr_step.outputs.pr_number }}..."
          
          # ใช้ --merge (แบบ merge commit) และ --delete-branch (ลบกิ่ง)
          # ตัด --auto ออกเพื่อให้สั่ง Merge ทันที
          gh pr merge ${{ steps.cpr_step.outputs.pr_number }} --merge --delete-branch
          
          echo "✅ เรียบร้อย! รวมงานเข้า Main และลบกิ่ง ${{ github.ref_name }} แล้ว"